### ISSUE TITLE
Can't load ruleset from releases

### ISSUE THREAD

**Issue by ChervyachokMigo** [Artemis-chan/osu-DIVA#119]
I copy it as any rulesets but I get some errors.
![image](https://user-images.githubusercontent.com/74270643/212430888-f0560dd0-18d7-47f4-82b5-12ae6c56444c.png)

logs:
2023-01-13 22:25:01 [verbose]: ----------------------------------------------------------
2023-01-13 22:25:01 [verbose]: runtime Log for Администратор (LogLevel: Verbose)
2023-01-13 22:25:01 [verbose]: Running osu 2022.1228.0.0 on .NET 6.0.2
2023-01-13 22:25:01 [verbose]: Environment: Windows (Microsoft Windows NT 10.0.19042.0), 6 cores
2023-01-13 22:25:01 [verbose]: ----------------------------------------------------------
2023-01-13 22:25:01 [verbose]: Updated display mode to desktop resolution: 1920x1080@60, SDL_PIXELFORMAT_RGB888
2023-01-13 22:25:01 [verbose]: GL Initialized
2023-01-13 22:25:01 [verbose]: GL Version:                 4.3.12618 Compatibility Profile Context 13.251.0.0
2023-01-13 22:25:01 [verbose]: GL Renderer:                AMD Radeon HD 6900 Series
2023-01-13 22:25:01 [verbose]: GL Shader Language version: 4.30
2023-01-13 22:25:01 [verbose]: GL Vendor:                  ATI Technologies Inc.
2023-01-13 22:25:01 [verbose]: GL Extensions:              GL_AMDX_debug_output GL_AMDX_vertex_shader_tessellator GL_AMD_blend_minmax_factor GL_AMD_conservative_depth GL_AMD_debug_output GL_AMD_depth_clamp_separate GL_AMD_draw_buffers_blend GL_AMD_multi_draw_indirect GL_AMD_name_gen_delete GL_AMD_performance_monitor GL_AMD_pinned_memory GL_AMD_query_buffer_object GL_AMD_sample_positions GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_atomic_counter_ops GL_AMD_shader_stencil_export GL_AMD_shader_trace GL_AMD_texture_cube_map_array GL_AMD_texture_texture4 GL_AMD_transform_feedback3_lines_triangles GL_AMD_vertex_shader_layer GL_AMD_vertex_shader_tessellator GL_AMD_vertex_shader_viewport_index GL_ARB_ES2_compatibility GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_blend_func_extended GL_ARB_clear_buffer_object GL_ARB_color_buffer_float GL_ARB_compatibility GL_ARB_compressed_texture_pixel_storage GL_ARB_compute_shader GL_ARB_conservative_depth GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_draw_indirect GL_ARB_draw_instanced GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_geometry_shader4 GL_ARB_get_program_binary GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_draw_indirect GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counters GL_ARB_shader_bit_encoding GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_stencil_export GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_shadow GL_ARB_shadow_ambient GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_border_clamp GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_cube_map_array GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_mirrored_repeat GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_snorm GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transpose_matrix GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_64bit GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ARB_window_pos GL_ATI_draw_buffers GL_ATI_envmap_bumpmap GL_ATI_fragment_shader GL_ATI_separate_stencil GL_ATI_texture_compression_3dc GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_ATI_texture_mirror_once GL_EXT_abgr GL_EXT_bgra GL_EXT_bindable_uniform GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_compiled_vertex_array GL_EXT_copy_buffer GL_EXT_copy_texture GL_EXT_direct_state_access GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_histogram GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_packed_pixels GL_EXT_pixel_buffer_object GL_EXT_point_parameters GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_specular_color GL_EXT_shader_image_load_store GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_EXT_subtexture GL_EXT_texgen_reflection GL_EXT_texture3D GL_EXT_texture_array GL_EXT_texture_buffer_object GL_EXT_texture_compression_bptc GL_EXT_texture_compression_latc GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_cube_map GL_EXT_texture_edge_clamp GL_EXT_texture_env_add GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod GL_EXT_texture_lod_bias GL_EXT_texture_mirror_clamp GL_EXT_texture_object GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_sRGB_decode GL_EXT_texture_shared_exponent GL_EXT_texture_snorm GL_EXT_texture_storage GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array GL_EXT_vertex_array_bgra GL_EXT_vertex_attrib_64bit GL_IBM_texture_mirrored_repeat GL_KHR_debug GL_KTX_buffer_region GL_NV_blend_square GL_NV_conditional_render GL_NV_copy_depth_to_color GL_NV_copy_image GL_NV_explicit_multisample GL_NV_float_buffer GL_NV_half_float GL_NV_primitive_restart GL_NV_texgen_reflection GL_NV_texture_barrier GL_SGIS_generate_mipmap GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_SUN_multi_draw_arrays GL_WIN_swap_hint WGL_EXT_swap_control
2023-01-13 22:25:01 [verbose]: Host execution state changed to Running
2023-01-13 22:25:01 [verbose]: Execution mode changed to SingleThread
2023-01-13 22:25:02 [verbose]: Beginning realm file store cleanup
2023-01-13 22:25:03 [verbose]: Finished realm file store cleanup (0 of 226786 deleted)
2023-01-13 22:25:03 [error]: Could not load ruleset "Diva". Please check for an update from the developer.
2023-01-13 22:25:03 [verbose]: Ruleset load failed: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
2023-01-13 22:25:03 [verbose]: Method 'get_Description' in type 'osu.Game.Rulesets.Diva.Mods.DivaModKey1' from assembly 'osu.Game.Rulesets.Diva, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
2023-01-13 22:25:03 [verbose]: Method 'get_Description' in type 'osu.Game.Rulesets.Diva.Mods.DivaModKey2' from assembly 'osu.Game.Rulesets.Diva, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
2023-01-13 22:25:03 [verbose]: Method 'get_Description' in type 'osu.Game.Rulesets.Diva.Mods.DivaModKey3' from assembly 'osu.Game.Rulesets.Diva, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
2023-01-13 22:25:03 [verbose]: Method 'get_Description' in type 'osu.Game.Rulesets.Diva.Mods.DivaModKey4' from assembly 'osu.Game.Rulesets.Diva, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
2023-01-13 22:25:03 [verbose]: Method 'get_Description' in type 'osu.Game.Rulesets.Diva.Mods.DivaModNoDoubles' from assembly 'osu.Game.Rulesets.Diva, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
2023-01-13 22:25:03 [verbose]: at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
2023-01-13 22:25:03 [verbose]: at System.Reflection.Assembly.GetTypes()
2023-01-13 22:25:03 [verbose]: at osu.Game.Rulesets.RulesetStore.addRuleset(Assembly assembly)
2023-01-13 22:25:03 [verbose]: System.TypeLoadException: Method 'get_Description' in type 'osu.Game.Rulesets.Diva.Mods.DivaModKey1' from assembly 'osu.Game.Rulesets.Diva, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
2023-01-13 22:25:03 [verbose]: System.TypeLoadException: Method 'get_Description' in type 'osu.Game.Rulesets.Diva.Mods.DivaModKey2' from assembly 'osu.Game.Rulesets.Diva, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
2023-01-13 22:25:03 [verbose]: System.TypeLoadException: Method 'get_Description' in type 'osu.Game.Rulesets.Diva.Mods.DivaModKey3' from assembly 'osu.Game.Rulesets.Diva, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
2023-01-13 22:25:03 [verbose]: System.TypeLoadException: Method 'get_Description' in type 'osu.Game.Rulesets.Diva.Mods.DivaModKey4' from assembly 'osu.Game.Rulesets.Diva, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
2023-01-13 22:25:03 [verbose]: System.TypeLoadException: Method 'get_Description' in type 'osu.Game.Rulesets.Diva.Mods.DivaModNoDoubles' from assembly 'osu.Game.Rulesets.Diva, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
2023-01-13 22:25:03 [error]: Could not load ruleset "resources". Please check for an update from the developer.
2023-01-13 22:25:03 [verbose]: Ruleset load failed: System.InvalidOperationException: Sequence contains no matching element
2023-01-13 22:25:03 [verbose]: at System.Linq.ThrowHelper.ThrowNoMatchException()
2023-01-13 22:25:03 [verbose]: at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
2023-01-13 22:25:03 [verbose]: at osu.Game.Rulesets.RulesetStore.addRuleset(Assembly assembly)
2023-01-13 22:25:03 [error]: Could not load ruleset "resources". Please check for an update from the developer.
2023-01-13 22:25:03 [verbose]: Ruleset load failed: System.InvalidOperationException: Sequence contains no matching element
2023-01-13 22:25:03 [verbose]: at System.Linq.ThrowHelper.ThrowNoMatchException()
2023-01-13 22:25:03 [verbose]: at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
2023-01-13 22:25:03 [verbose]: at osu.Game.Rulesets.RulesetStore.addRuleset(Assembly assembly)
2023-01-13 22:25:03 [error]: Could not load ruleset "resources". Please check for an update from the developer.
2023-01-13 22:25:03 [verbose]: Ruleset load failed: System.InvalidOperationException: Sequence contains no matching element
2023-01-13 22:25:03 [verbose]: at System.Linq.ThrowHelper.ThrowNoMatchException()
2023-01-13 22:25:03 [verbose]: at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
2023-01-13 22:25:03 [verbose]: at osu.Game.Rulesets.RulesetStore.addRuleset(Assembly assembly)
2023-01-13 22:25:03 [error]: Could not load ruleset "resources". Please check for an update from the developer.
2023-01-13 22:25:03 [verbose]: Ruleset load failed: System.InvalidOperationException: Sequence contains no matching element
2023-01-13 22:25:03 [verbose]: at System.Linq.ThrowHelper.ThrowNoMatchException()
2023-01-13 22:25:03 [verbose]: at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
2023-01-13 22:25:03 [verbose]: at osu.Game.Rulesets.RulesetStore.addRuleset(Assembly assembly)
2023-01-13 22:25:03 [error]: Could not load ruleset "resources". Please check for an update from the developer.
2023-01-13 22:25:03 [verbose]: Ruleset load failed: System.InvalidOperationException: Sequence contains no matching element
2023-01-13 22:25:03 [verbose]: at System.Linq.ThrowHelper.ThrowNoMatchException()
2023-01-13 22:25:03 [verbose]: at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
2023-01-13 22:25:03 [verbose]: at osu.Game.Rulesets.RulesetStore.addRuleset(Assembly assembly)
2023-01-13 22:25:03 [verbose]: Updated display mode to desktop resolution: 1920x1080@60, SDL_PIXELFORMAT_RGB888
2023-01-13 22:25:03 [verbose]: Opened realm "C:\Users\Администратор\AppData\Roaming\osu\client.realm" at version 25
2023-01-13 22:25:04 [verbose]: Loading FPSCounter...
2023-01-13 22:25:04 [verbose]: 🔈 BASS initialised
2023-01-13 22:25:04 [verbose]: BASS version:           2.4.16.7
2023-01-13 22:25:04 [verbose]: BASS FX version:        2.4.12.6
2023-01-13 22:25:04 [verbose]: BASS MIX version:       2.4.11.1
2023-01-13 22:25:04 [verbose]: Device:                 Default
2023-01-13 22:25:04 [verbose]: Driver:
2023-01-13 22:25:04 [verbose]: Update period:          5 ms
2023-01-13 22:25:04 [verbose]: Device buffer length:   10 ms
2023-01-13 22:25:04 [verbose]: Playback buffer length: 100 ms
2023-01-13 22:25:04 [verbose]: Loaded FPSCounter!
2023-01-13 22:25:04 [verbose]: Loading VersionManager...
2023-01-13 22:25:04 [verbose]: Loaded VersionManager!
2023-01-13 22:25:04 [verbose]: Loading OsuLogo...
2023-01-13 22:25:04 [verbose]: Loaded OsuLogo!
2023-01-13 22:25:04 [verbose]: Loading Toolbar...
2023-01-13 22:25:04 [verbose]: 📺 OsuScreenStack#431(depth:1) loading Loader#346
2023-01-13 22:25:04 [verbose]: 📺 OsuScreenStack#431(depth:1) entered Loader#346
2023-01-13 22:25:04 [verbose]: Loaded Toolbar!
2023-01-13 22:25:04 [verbose]: Loading VolumeOverlay...
2023-01-13 22:25:05 [verbose]: Loaded VolumeOverlay!
2023-01-13 22:25:05 [verbose]: Loading OnScreenDisplay...
2023-01-13 22:25:05 [verbose]: Loaded OnScreenDisplay!
2023-01-13 22:25:05 [verbose]: Loading NotificationOverlay...
2023-01-13 22:25:05 [verbose]: Loaded NotificationOverlay!
2023-01-13 22:25:05 [verbose]: Loading LegacyImportManager...
2023-01-13 22:25:05 [verbose]: Loaded LegacyImportManager!
2023-01-13 22:25:05 [verbose]: Loading ScreenshotManager...
2023-01-13 22:25:05 [verbose]: Loaded ScreenshotManager!
2023-01-13 22:25:05 [verbose]: Loading SquirrelUpdateManager...
2023-01-13 22:25:05 [verbose]: Loaded SquirrelUpdateManager!
2023-01-13 22:25:05 [verbose]: Loading FirstRunSetupOverlay...
2023-01-13 22:25:05 [verbose]: Loaded FirstRunSetupOverlay!
2023-01-13 22:25:05 [verbose]: Loading ManageCollectionsDialog...
2023-01-13 22:25:05 [verbose]: Loaded ManageCollectionsDialog!
2023-01-13 22:25:05 [verbose]: Loading BeatmapListingOverlay...
2023-01-13 22:25:05 [verbose]: 📺 OsuScreenStack#431(depth:1) suspended Loader#346 (waiting on Disclaimer#582)
2023-01-13 22:25:05 [verbose]: 📺 OsuScreenStack#431(depth:2) entered Disclaimer#582
2023-01-13 22:25:05 [verbose]: Loaded BeatmapListingOverlay!
2023-01-13 22:25:05 [verbose]: Loading DashboardOverlay...
2023-01-13 22:25:05 [verbose]: Loaded DashboardOverlay!
2023-01-13 22:25:05 [verbose]: Loading NewsOverlay...
2023-01-13 22:25:05 [verbose]: Loaded NewsOverlay!
2023-01-13 22:25:05 [verbose]: Loading RankingsOverlay...
2023-01-13 22:25:05 [verbose]: Loaded RankingsOverlay!
2023-01-13 22:25:05 [verbose]: Loading ChannelManager...
2023-01-13 22:25:05 [verbose]: Loaded ChannelManager!
2023-01-13 22:25:05 [verbose]: Loading ChatOverlay...
2023-01-13 22:25:05 [verbose]: Loaded ChatOverlay!
2023-01-13 22:25:05 [verbose]: Loading MessageNotifier...
2023-01-13 22:25:05 [verbose]: Loaded MessageNotifier!
2023-01-13 22:25:05 [verbose]: Loading SettingsOverlay...
2023-01-13 22:25:05 [verbose]: Loaded SettingsOverlay!
2023-01-13 22:25:05 [verbose]: Loading ChangelogOverlay...
2023-01-13 22:25:06 [verbose]: Loaded ChangelogOverlay!
2023-01-13 22:25:06 [verbose]: Loading UserProfileOverlay...
2023-01-13 22:25:06 [verbose]: Loaded UserProfileOverlay!
2023-01-13 22:25:06 [verbose]: Loading BeatmapSetOverlay...
2023-01-13 22:25:06 [verbose]: Loaded BeatmapSetOverlay!
2023-01-13 22:25:06 [verbose]: Loading WikiOverlay...
2023-01-13 22:25:06 [verbose]: Loaded WikiOverlay!
2023-01-13 22:25:06 [verbose]: Loading SkinEditorOverlay...
2023-01-13 22:25:06 [verbose]: Loaded SkinEditorOverlay!
2023-01-13 22:25:06 [verbose]: Loading LoginOverlay...
2023-01-13 22:25:06 [verbose]: Loaded LoginOverlay!
2023-01-13 22:25:06 [verbose]: Loading NowPlayingOverlay...
2023-01-13 22:25:06 [verbose]: Loaded NowPlayingOverlay!
2023-01-13 22:25:06 [verbose]: Loading AccountCreationOverlay...
2023-01-13 22:25:06 [verbose]: 📺 ScreenStack#173(depth:1) scheduling push ScreenWelcome#497
2023-01-13 22:25:06 [verbose]: Loaded AccountCreationOverlay!
2023-01-13 22:25:06 [verbose]: Loading DialogOverlay...
2023-01-13 22:25:06 [verbose]: Loaded DialogOverlay!
2023-01-13 22:25:06 [verbose]: Loading HighPerformanceSession...
2023-01-13 22:25:06 [verbose]: Loaded HighPerformanceSession!
2023-01-13 22:25:06 [verbose]: Loading BackgroundBeatmapProcessor...
2023-01-13 22:25:06 [verbose]: Loaded BackgroundBeatmapProcessor!
2023-01-13 22:25:06 [verbose]: Beginning background beatmap processing..
2023-01-13 22:25:06 [verbose]: Querying for beatmap sets to reprocess...
2023-01-13 22:25:06 [verbose]: Found 0 beatmap sets which require reprocessing.
2023-01-13 22:25:06 [verbose]: Querying for scores to reprocess...
2023-01-13 22:25:06 [verbose]: Found 0 scores which require reprocessing.
2023-01-13 22:25:06 [verbose]: Finished background beatmap processing!
2023-01-13 22:25:11 [verbose]: 📺 OsuScreenStack#431(depth:2) suspended Disclaimer#582 (waiting on IntroCircles#537)
2023-01-13 22:25:11 [verbose]: 📺 OsuScreenStack#431(depth:3) entered IntroCircles#537
2023-01-13 22:25:11 [verbose]: 📺 BackgroundScreenStack#205(depth:1) loading BackgroundScreenDefault#172
2023-01-13 22:25:12 [verbose]: Game-wide working beatmap updated to Mark Mothersbaugh & John Enroth - Eureka On My Mind Reprise (The_Priest_In_Yellow) [A what-gate?]
2023-01-13 22:25:12 [verbose]: 🌅 Background change queued
2023-01-13 22:25:12 [verbose]: 📺 BackgroundScreenStack#205(depth:1) entered BackgroundScreenDefault#172
2023-01-13 22:25:12 [verbose]: decoupled ruleset transferred ("" -> "osu!")
2023-01-13 22:25:14 [verbose]: 📺 OsuScreenStack#431(depth:3) suspended IntroCircles#537 (waiting on MainMenu#600)
2023-01-13 22:25:14 [verbose]: 📺 OsuScreenStack#431(depth:4) entered MainMenu#600
2023-01-13 22:25:15 [verbose]: ⚠️ Could not load ruleset "Diva". Please check for an update from the developer.
2023-01-13 22:25:15 [verbose]: ⚠️ Could not load ruleset "resources". Please check for an update from the developer.
2023-01-13 22:25:15 [verbose]: ⚠️ Could not load ruleset "resources". Please check for an update from the developer.
2023-01-13 22:25:15 [verbose]: ⚠️ Subsequent messages have been logged. Click to view log files.
2023-01-13 22:25:15 [verbose]: ⚠️ Running osu! as administrator does not improve performance, may break integrations and poses a security risk. Please run the game as a normal user.
2023-01-13 22:25:47 [verbose]: Game-wide working beatmap updated to Adore Delano - I Adore U (Gabe) [Easy]
2023-01-13 22:25:47 [verbose]: 🌅 Background change queued
2023-01-13 22:26:24 [verbose]: ButtonSystem's state changed from Initial to TopLevel
2023-01-13 22:26:25 [verbose]: Focus contention triggered by NotificationOverlay.

**Comment by Artemis-chan** [comment]
try this please https://github.com/Artemis-chan/osu-DIVA/suites/10380258898/artifacts/512192262

**Comment by ChervyachokMigo** [comment]
launched thanks!
