### ISSUE TITLE
2023.305.0 crash on pressing a note

### ISSUE THREAD

**Issue by roriloty** [Artemis-chan/osu-DIVA#134]
when i was trying to press the note, the game just froze and crash. here is the runtime.log:

2023-07-04 06:26:08 [error]: An unhandled error has occurred.
2023-07-04 06:26:08 [error]: System.InvalidCastException: Cannot convert bindable of type osu.Framework.Bindables.BindableDouble retrieved from ConfigManager to osu.Framework.Bindables.Bindable`1[System.Boolean].
2023-07-04 06:26:08 [error]: at osu.Framework.Configuration.ConfigManager`1.GetOriginalBindable[TValue](TLookup lookup)
2023-07-04 06:26:08 [error]: at osu.Framework.Configuration.ConfigManager`1.Get[TValue](TLookup lookup)
2023-07-04 06:26:08 [error]: at osu.Game.Rulesets.Diva.Objects.Drawables.DrawableDivaJudgement.ApplyHitAnimations()
2023-07-04 06:26:08 [error]: at osu.Game.Rulesets.Judgements.DrawableJudgement.runAnimation()
2023-07-04 06:26:08 [error]: at osu.Game.Rulesets.Judgements.DrawableJudgement.PrepareForUse()
2023-07-04 06:26:08 [error]: at osu.Game.Rulesets.Diva.Objects.Drawables.DrawableDivaJudgement.PrepareForUse()
2023-07-04 06:26:08 [error]: at osu.Framework.Graphics.Pooling.PoolableDrawable.Update()

**Comment by Thesola10** [comment]
does the issue still occur with [the latest debug build](https://github.com/Artemis-chan/osu-DIVA/suites/14337570327/artifacts/807022049)?

**Comment by Thesola10** [comment]
Just tested and the issue does not occur on the latest build+latest lazer, I'll flag a new release and close this
