### ISSUE TITLE
Unable to load beatmapsets

### ISSUE THREAD

**Issue by ABKQPO** [Artemis-chan/osu-DIVA#157]
```

2024-11-17 13:11:15 [verbose]: Song select working beatmap updated to Ardolf - Split EX (Instrumental Ver.) (Ixcors) [REALITIES COLLIDE]
2024-11-17 13:11:16 [verbose]: Song select updating selection with beatmap: Ardolf - Split EX (Instrumental Ver.) (Ixcors) [REALITIES COLLIDE] f72e57d5-750b-4bfd-b155-62dfb67d6239 ruleset:diva
2024-11-17 13:11:16 [verbose]: decoupled ruleset transferred ("hishigata" -> "osu!DIVA")
2024-11-17 13:11:17 [verbose]: 📺 OsuScreenStack#269(depth:4) suspended PlaySongSelect#459 (waiting on PlayerLoader#267)
2024-11-17 13:11:17 [verbose]: 📺 OsuScreenStack#269(depth:5) loading PlayerLoader#267
2024-11-17 13:11:17 [verbose]: 📺 OsuScreenStack#269(depth:5) entered PlayerLoader#267
2024-11-17 13:11:18 [error]: An unhandled error has occurred.
2024-11-17 13:11:18 [error]: System.MissingMethodException: Method not found: 'Void osu.Game.Audio.HitSampleInfo..ctor(System.String, System.String, System.String, Int32)'.
2024-11-17 13:11:18 [error]: at osu.Game.Rulesets.Diva.Objects.Drawables.DrawableDivaHitObject.GetSamples()
2024-11-17 13:11:18 [error]: at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.LoadSamples()
2024-11-17 13:11:18 [error]: at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.OnApply(HitObjectLifetimeEntry entry)
2024-11-17 13:11:18 [error]: at osu.Game.Rulesets.Objects.Pooling.PoolableDrawableWithLifetime`1.LoadAsyncComplete()
2024-11-17 13:11:18 [error]: at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.LoadAsyncComplete()
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.AddInternal(Drawable drawable)
2024-11-17 13:11:18 [error]: at osu.Game.Rulesets.UI.HitObjectContainer.Add(DrawableHitObject drawable)
2024-11-17 13:11:18 [error]: at osu.Game.Rulesets.UI.Playfield.Add(DrawableHitObject h)
2024-11-17 13:11:18 [error]: at osu.Game.Rulesets.UI.DrawableRuleset`1.AddHitObject(TObject hitObject)
2024-11-17 13:11:18 [error]: at osu.Game.Rulesets.UI.DrawableRuleset`1.loadObjects(CancellationToken cancellationToken)
2024-11-17 13:11:18 [error]: at osu.Game.Rulesets.UI.DrawableRuleset`1.load(Nullable`1 cancellationToken)
2024-11-17 13:11:18 [error]: at osu.Game.Rulesets.UI.DrawableRuleset`1.<>c.<RegisterForDependencyActivation>b__82_0(Object t, IReadOnlyDependencyContainer d)
2024-11-17 13:11:18 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[T](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2024-11-17 13:11:18 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[T](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2024-11-17 13:11:18 [error]: at osu.Framework.Allocation.DependencyActivator.Activate[T](T obj, IReadOnlyDependencyContainer dependencies)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.InjectDependencies(IReadOnlyDependencyContainer dependencies)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.<>c.<RegisterForDependencyActivation>b__209_0(Object t, IReadOnlyDependencyContainer d)
2024-11-17 13:11:18 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[T](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2024-11-17 13:11:18 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[T](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2024-11-17 13:11:18 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[T](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2024-11-17 13:11:18 [error]: at osu.Framework.Allocation.DependencyActivator.Activate[T](T obj, IReadOnlyDependencyContainer dependencies)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.InjectDependencies(IReadOnlyDependencyContainer dependencies)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.<>c.<RegisterForDependencyActivation>b__209_0(Object t, IReadOnlyDependencyContainer d)
2024-11-17 13:11:18 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[T](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2024-11-17 13:11:18 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[T](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2024-11-17 13:11:18 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[T](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2024-11-17 13:11:18 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[T](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2024-11-17 13:11:18 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[T](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2024-11-17 13:11:18 [error]: at osu.Framework.Allocation.DependencyActivator.Activate[T](T obj, IReadOnlyDependencyContainer dependencies)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.InjectDependencies(IReadOnlyDependencyContainer dependencies)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.<>c.<RegisterForDependencyActivation>b__209_0(Object t, IReadOnlyDependencyContainer d)
2024-11-17 13:11:18 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[T](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2024-11-17 13:11:18 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[T](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2024-11-17 13:11:18 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[T](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2024-11-17 13:11:18 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[T](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2024-11-17 13:11:18 [error]: at osu.Framework.Allocation.DependencyActivator.Activate[T](T obj, IReadOnlyDependencyContainer dependencies)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.InjectDependencies(IReadOnlyDependencyContainer dependencies)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.<>c.<RegisterForDependencyActivation>b__209_0(Object t, IReadOnlyDependencyContainer d)
2024-11-17 13:11:18 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[T](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2024-11-17 13:11:18 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[T](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2024-11-17 13:11:18 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[T](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2024-11-17 13:11:18 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[T](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2024-11-17 13:11:18 [error]: at osu.Framework.Allocation.DependencyActivator.Activate[T](T obj, IReadOnlyDependencyContainer dependencies)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.InjectDependencies(IReadOnlyDependencyContainer dependencies)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.load(ShaderManager shaders, Nullable`1 cancellation)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.<>c.<RegisterForDependencyActivation>b__209_0(Object t, IReadOnlyDependencyContainer d)
2024-11-17 13:11:18 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[T](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2024-11-17 13:11:18 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[T](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2024-11-17 13:11:18 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[T](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2024-11-17 13:11:18 [error]: at osu.Framework.Allocation.DependencyActivator.Activate[T](T obj, IReadOnlyDependencyContainer dependencies)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.InjectDependencies(IReadOnlyDependencyContainer dependencies)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.AddInternal(Drawable drawable)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.Container`1.AddInternal(Drawable drawable)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.AddRangeInternal(IEnumerable`1 range)
2024-11-17 13:11:18 [error]: at osu.Game.Screens.Play.FailAnimationContainer.load(AudioManager audio, IBindable`1 beatmap)
2024-11-17 13:11:18 [error]: at osu.Game.Screens.Play.FailAnimationContainer.<>c.<RegisterForDependencyActivation>b__33_0(Object t, IReadOnlyDependencyContainer d)
2024-11-17 13:11:18 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[T](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2024-11-17 13:11:18 [error]: at osu.Framework.Allocation.DependencyActivator.Activate[T](T obj, IReadOnlyDependencyContainer dependencies)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.InjectDependencies(IReadOnlyDependencyContainer dependencies)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.AddInternal(Drawable drawable)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.Container`1.AddInternal(Drawable drawable)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.Container`1.AddRange(IEnumerable`1 range)
2024-11-17 13:11:18 [error]: at osu.Game.Screens.Play.Player.load(OsuConfigManager config, OsuGameBase game, CancellationToken cancellationToken)
2024-11-17 13:11:18 [error]: at osu.Game.Screens.Play.Player.<>c.<RegisterForDependencyActivation>b__168_0(Object t, IReadOnlyDependencyContainer d)
2024-11-17 13:11:18 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[T](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2024-11-17 13:11:18 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[T](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2024-11-17 13:11:18 [error]: at osu.Framework.Allocation.DependencyActivator.Activate[T](T obj, IReadOnlyDependencyContainer dependencies)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.InjectDependencies(IReadOnlyDependencyContainer dependencies)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Drawable.LoadFromAsync(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadComponents[TLoadable](List`1 components, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext, CancellationToken cancellation)
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.<>c__DisplayClass13_0`1.<LoadComponentsAsync>b__1()
2024-11-17 13:11:18 [error]: at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2024-11-17 13:11:18 [error]: --- End of stack trace from previous location ---
2024-11-17 13:11:18 [error]: at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2024-11-17 13:11:18 [error]: at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2024-11-17 13:11:18 [error]: --- End of stack trace from previous location ---
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.<>c__DisplayClass13_2`1.<LoadComponentsAsync>b__4()
2024-11-17 13:11:18 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2024-11-17 13:11:18 [error]: at osu.Framework.Threading.Scheduler.Update()
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 13:11:18 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2024-11-17 13:11:18 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2024-11-17 13:11:18 [error]: at osu.Framework.Threading.GameThread.processFrame()
```

**Comment by LukaTV939** [comment]
for me the ruleset just doesn't load at all on latest
